spring:
  application:
    name: BLPS_Lab1
  datasource:
    url: jdbc:postgresql://localhost:5432/first
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mail.ru
    port: 465
    username: hokure04@mail.ru
    password: aHXm4xap2rkyg4dS4hL5
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
minio: 
  root:
    username:
      JABA_SUPER_USER_MINIO
    pwd:
      jaba127!368601NO
    access_key:
      JABA_SUPER_USER_MINIO
    secret_key:
      jaba127!368601NO
  # database-platform: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: Q5v1CXQ1Y64cayU84BnlR3Az9fVFe8Bvn6Mrf68bX5U=